sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Publish docs"
      script:
        - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ -e 'ASCIIDOCTOR_THEME=riak' integr8/alpine-asciidoctor-helper html docs/index.adoc
      deploy:
        provider: pages
        target-branch: gh-pages
        skip_cleanup: true
        local_dir: output/
        github_token: $GH_TOKEN
        on:
          branch: development
