sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Pre-build"
      script: 
        - wget https://github.com/docker-slim/docker-slim/releases/download/1.22/dist_linux.tar.gz -O dockerslim.tar.gz
        - tar -xvzf dockerslim.tar.gz
        - rm dockerslim.tar.gz
        - sudo mv dist_linux/* /usr/local/bin/
        - rm -rf dist_linux
        - docker-slim
    - stage: "Build Image"
      script:
        - docker build -t integr8/alpine-liquibase-helper .
    - stage: "Minimify image"
      script:
        - docker-slim --state-path $(pwd) build --tag integr8/alpine-liquibase-helper:slim integr8/alpine-liquibase-helper 
    
